runtime_mode: "SIMULATION" # SIMULATION or REALTIME
realtime:
  clock_tick_duration: "10.0"
  clock_timestamp_increase_per_tick: "None"
  clock_start_timestamp: "!!timestamp!None"
  analyzer_sleep_duration: "30.0 * MINUTE_SECONDS"
  nice_hash_sleep_duration: "1.0 * MINUTE_SECONDS"
  controller_sleep_duration: "10.0 * MINUTE_SECONDS"
  mine_db_updater_sleep_duration: "1.0 * MINUTE_SECONDS"
  simulation_db_updater_sleep_duration: "1.0 * MINUTE_SECONDS"
  simulation_evaluator_sleep_duration: "1.0 * MINUTE_SECONDS"
  nice_hash_close_orders_before_shutdown: "True"
  log_level: "logging.INFO"
  log_format: "|||%(asctime)s - %(name)s -  %(levelname)s - %(message)s"
  db_host: "|||127.0.0.1"
  db_port: "|||5432"
  db_user: "|||smart_miner"
  db_password: "|||smartminerpa$$w0rd1368"
  db_database_name: "|||smart_miner"
  db_simulation_database_name: "|||smart_miner_simulation_data"
  db_csv_data_dir: "|||/home/jamshid/PycharmProjects/smart-miner/files/csv_data/"
  db_csv_separator: "|||,"
simulation:
  clock_tick_duration: "0.05"
  clock_timestamp_increase_per_tick: "1.0 * MINUTE_SECONDS"
  clock_start_timestamp: "!!timestamp!|||11/22/2019-23:16:24"
  simulation_end_timestamp: "!!timestamp!|||01/22/2020-23:16:24"
  log_level: "logging.INFO"
  clean_simulation_database: "True"
  identifier: "|||a_simulation"
  simulation_summaries_data_dir: "|||/home/jamshid/PycharmProjects/smart-miner/files/simulations/"
